version: "3"

services: 
    app:
        build: .
        command: npm start
        ports: 
            - "3000:3000"
            - "9229:9229" #debug port
        volumes: 
            - .:/usr/app