@urlapi = http://localhost:3000

### 
# @name get
get {{urlapi}}/produtos HTTP/1.1
content-type: application/json

### 
# @name getByPK
get {{urlapi}}/produtos/1 HTTP/1.1
content-type: application/json

### 
# @name delete
delete {{urlapi}}/produtos/1 HTTP/1.1
content-type: application/json

###
# @name create
post {{urlapi}}/produtos
content-type: application/json

{    
    "nome": "sabão",
    "quantidade": "5",
    "preco": "500"
}

###
# @name update
put {{urlapi}}/produtos
content-type: application/json

{
    "id":1,
    "nome": "sabão krakra",
    "quantidade": "5",
    "preco": "500"
}